runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: "rottengcloud_wanglin_bucket"

handlers:
  - url: /
    static_files: dist/MonstyrApp/index.html
    upload: dist/MonstyrApp/index.html

  - url: /
    static_dir: dist/MonstyrApp
