runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: "rubyduckies_cloudstorage"

handlers:
  - url: /
    static_files: dist/monstyr-app/index.html
    upload: dist/monstyr-app/index.html

  - url: /
    static_dir: dist/monstyr-app
