# [START cloudrun_rails_cloudbuild]
steps:

# STEP 0: BUILD IMAGE
- id: "build image"
  name: "gcr.io/cloud-builders/docker"
  entrypoint: 'bash'
  args: ["-c", "docker build --build-arg MASTER_KEY=$$RAILS_KEY -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} . "]
  secretEnv: ["RAILS_KEY"]



# STEP 1: PUSH IMAGE
- id: "push image"
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]



# STEP 2: APPLY MIGRATIONS
- id: "apply migrations"
  name: "gcr.io/google-appengine/exec-wrapper"
  entrypoint: "bash"
  args:
    [
      "-c",
      "/buildstep/execute.sh -i gcr.io/${PROJECT_ID}/${_SERVICE_NAME} -s ${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME} -e RAILS_MASTER_KEY=$$RAILS_KEY -- bundle exec rails db:migrate"
    ]
  secretEnv: ["RAILS_KEY"]



# STEP 3: RUN DEPLOY
- id: "run deploy"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
    [
      "run", "deploy",
      "${_SERVICE_NAME}",
      "--platform", "managed",
      "--region", "${_REGION}",
      "--image", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
      "--add-cloudsql-instances", "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
      "--allow-unauthenticated"
    ]



# SUBSTITUTIONS
substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: rubyduckies-rails-backend
  _INSTANCE_NAME: rubyduckies-cloudsql
  _SECRET_NAME: rubyduckies-rails-backend-secret



# GOOGLE SECRET MANAGER
availableSecrets:
  secretManager:
  - versionName: projects/820616993981/secrets/${_SECRET_NAME}/versions/latest
    env: "RAILS_KEY"



images:
- "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
# [END cloudrun_rails_cloudbuild]
