require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/liveposts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Livepost. As you add validations to Livepost, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Livepost.create! valid_attributes
      get liveposts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      livepost = Livepost.create! valid_attributes
      get livepost_url(livepost)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_livepost_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      livepost = Livepost.create! valid_attributes
      get edit_livepost_url(livepost)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Livepost" do
        expect {
          post liveposts_url, params: { livepost: valid_attributes }
        }.to change(Livepost, :count).by(1)
      end

      it "redirects to the created livepost" do
        post liveposts_url, params: { livepost: valid_attributes }
        expect(response).to redirect_to(livepost_url(Livepost.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Livepost" do
        expect {
          post liveposts_url, params: { livepost: invalid_attributes }
        }.to change(Livepost, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post liveposts_url, params: { livepost: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested livepost" do
        livepost = Livepost.create! valid_attributes
        patch livepost_url(livepost), params: { livepost: new_attributes }
        livepost.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the livepost" do
        livepost = Livepost.create! valid_attributes
        patch livepost_url(livepost), params: { livepost: new_attributes }
        livepost.reload
        expect(response).to redirect_to(livepost_url(livepost))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        livepost = Livepost.create! valid_attributes
        patch livepost_url(livepost), params: { livepost: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested livepost" do
      livepost = Livepost.create! valid_attributes
      expect {
        delete livepost_url(livepost)
      }.to change(Livepost, :count).by(-1)
    end

    it "redirects to the liveposts list" do
      livepost = Livepost.create! valid_attributes
      delete livepost_url(livepost)
      expect(response).to redirect_to(liveposts_url)
    end
  end
end
