require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pendingposts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Pendingpost. As you add validations to Pendingpost, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pendingpost.create! valid_attributes
      get pendingposts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pendingpost = Pendingpost.create! valid_attributes
      get pendingpost_url(pendingpost)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pendingpost_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      pendingpost = Pendingpost.create! valid_attributes
      get edit_pendingpost_url(pendingpost)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pendingpost" do
        expect {
          post pendingposts_url, params: { pendingpost: valid_attributes }
        }.to change(Pendingpost, :count).by(1)
      end

      it "redirects to the created pendingpost" do
        post pendingposts_url, params: { pendingpost: valid_attributes }
        expect(response).to redirect_to(pendingpost_url(Pendingpost.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pendingpost" do
        expect {
          post pendingposts_url, params: { pendingpost: invalid_attributes }
        }.to change(Pendingpost, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pendingposts_url, params: { pendingpost: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pendingpost" do
        pendingpost = Pendingpost.create! valid_attributes
        patch pendingpost_url(pendingpost), params: { pendingpost: new_attributes }
        pendingpost.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pendingpost" do
        pendingpost = Pendingpost.create! valid_attributes
        patch pendingpost_url(pendingpost), params: { pendingpost: new_attributes }
        pendingpost.reload
        expect(response).to redirect_to(pendingpost_url(pendingpost))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pendingpost = Pendingpost.create! valid_attributes
        patch pendingpost_url(pendingpost), params: { pendingpost: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pendingpost" do
      pendingpost = Pendingpost.create! valid_attributes
      expect {
        delete pendingpost_url(pendingpost)
      }.to change(Pendingpost, :count).by(-1)
    end

    it "redirects to the pendingposts list" do
      pendingpost = Pendingpost.create! valid_attributes
      delete pendingpost_url(pendingpost)
      expect(response).to redirect_to(pendingposts_url)
    end
  end
end
